version: '2'

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - asasalint
    - bodyclose
    - dupl
    - durationcheck
    - errname
    - exptostd
    - gosec
    - importas
    - iface
    - intrange
    - lll
    - musttag
    - nestif
    - nilerr
    - nilnil
    - noctx
    - perfsprint
    - prealloc
    - reassign
    - recvcheck
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - usestdlibvars
    - wrapcheck
    - gocritic
    - nilaway
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
      disabled-checks:
      - unnecessaryBlock
    govet:
      enable-all: true
    custom:
      nilaway:
        type: module
        settings:
          include-pkgs: ''
    gosec:
      excludes:
        - G404
  exclusions:
    paths:
      - '^.*\/mock.go$'
      - '^.*\/.*_test.go$'
      
formatters:
  enable:
    - gofmt
      
output:
  formats:
    text:
      path: stderr
  sort-order:
    - linter
    - severity
    - file
  show-stats: false

run:
  timeout: 10m
  tests: false
  allow-parallel-runners: true
  go: '1.24'

severity:
  default: error
  rules:
    - severity: warning
      linters:
        - dupl