version: '3.8'
name: prod-management-db

services:
  postgres:
    image: 'postgres:alpine'
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=prod_db
    ports:
      - '5434:5432'